services:
  web:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5555:5555

    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.mjs
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: